-- Generated by `rustio-admin startapp product`. Customise freely before
-- running `rustio-admin migrate apply` -- once a migration has been applied
-- editing this file no-ops; create a new numbered file instead.

CREATE TABLE products (
    id BIGSERIAL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "price" NUMERIC NOT NULL,
    "in_stock" BOOLEAN NOT NULL DEFAULT FALSE
);
