-- Generated by `rustio-admin startapp order`. Customise freely before
-- running `rustio-admin migrate apply` -- once a migration has been applied
-- editing this file no-ops; create a new numbered file instead.

CREATE TABLE orders (
    id BIGSERIAL PRIMARY KEY,
    "customer_id" BIGINT NOT NULL REFERENCES customers(id),
    "total" NUMERIC NOT NULL,
    "status" TEXT NOT NULL CHECK ("status" IN ('pending', 'paid', 'shipped', 'cancelled'))
);
