-- Generated by `rustio-admin startapp order_item`. Customise freely before
-- running `rustio-admin migrate apply` -- once a migration has been applied
-- editing this file no-ops; create a new numbered file instead.

CREATE TABLE order_items (
    id BIGSERIAL PRIMARY KEY,
    "order_id" BIGINT NOT NULL REFERENCES orders(id),
    "product_id" BIGINT NOT NULL REFERENCES products(id),
    "quantity" INTEGER NOT NULL,
    "unit_price" NUMERIC NOT NULL
);
