-- Generated by `rustio-admin startapp product_image`. Customise freely before
-- running `rustio-admin migrate apply` -- once a migration has been applied
-- editing this file no-ops; create a new numbered file instead.

CREATE TABLE product_images (
    id BIGSERIAL PRIMARY KEY,
    "product_id" BIGINT NOT NULL REFERENCES products(id),
    "url" TEXT NOT NULL,
    "alt_text" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "is_primary" BOOLEAN NOT NULL DEFAULT FALSE
);
