-- Generated by `rustio-admin startapp cart_item`. Customise freely before
-- running `rustio-admin migrate apply` -- once a migration has been applied
-- editing this file no-ops; create a new numbered file instead.

CREATE TABLE cart_items (
    id BIGSERIAL PRIMARY KEY,
    "customer_id" BIGINT NOT NULL REFERENCES customers(id),
    "product_id" BIGINT NOT NULL REFERENCES products(id),
    "quantity" INTEGER NOT NULL
);
