-- Generated by `rustio-admin startapp payment`. Customise freely before
-- running `rustio-admin migrate apply` -- once a migration has been applied
-- editing this file no-ops; create a new numbered file instead.

CREATE TABLE payments (
    id BIGSERIAL PRIMARY KEY,
    "order_id" BIGINT NOT NULL REFERENCES orders(id),
    "provider" TEXT NOT NULL,
    "method" TEXT NOT NULL,
    "transaction_id" TEXT NOT NULL,
    "amount" NUMERIC NOT NULL,
    "status" TEXT NOT NULL CHECK ("status" IN ('pending', 'completed', 'failed', 'refunded'))
);
