//! Generated by `rustio-admin startapp address`. Customise freely.

use rustio_admin::{Error, Model, ModelAdmin, Row, RustioAdmin, Value};

#[derive(RustioAdmin)]
pub struct Address {
    pub id: i64,
    pub customer_id: i64,
    pub recipient_name: String,
    pub line1: String,
    pub line2: String,
    pub city: String,
    pub postal_code: String,
    pub country: String,
    pub is_default: bool,
}

impl Model for Address {
    const TABLE: &'static str = "addresses";
    const COLUMNS: &'static [&'static str] = &["id", "customer_id", "recipient_name", "line1", "line2", "city", "postal_code", "country", "is_default"];
    const INSERT_COLUMNS: &'static [&'static str] = &["customer_id", "recipient_name", "line1", "line2", "city", "postal_code", "country", "is_default"];

    fn id(&self) -> i64 {
        self.id
    }

    fn from_row(row: Row<'_>) -> Result<Self, Error> {
        Ok(Self {
            id: row.get_i64("id")?,
            customer_id: row.get_i64("customer_id")?,
            recipient_name: row.get_string("recipient_name")?,
            line1: row.get_string("line1")?,
            line2: row.get_string("line2")?,
            city: row.get_string("city")?,
            postal_code: row.get_string("postal_code")?,
            country: row.get_string("country")?,
            is_default: row.get_bool("is_default")?,
        })
    }

    fn insert_values(&self) -> Vec<Value> {
        vec![self.customer_id.into(), self.recipient_name.clone().into(), self.line1.clone().into(), self.line2.clone().into(), self.city.clone().into(), self.postal_code.clone().into(), self.country.clone().into(), self.is_default.into()]
    }
}

// The `ModelAdmin` impl below customises the admin list / form
// surface for `Address`. Every method has a sensible default;
// these starter overrides reflect the fields you declared with
// `--field` at scaffold time. Edit freely.
impl ModelAdmin for Address {
    /// Columns shown in the list-page table. Order matches the
    /// `--field` declaration order.
    fn list_display() -> &'static [&'static str] {
        &["id", "customer_id", "recipient_name", "city", "country", "is_default"]
    }

    /// Columns whose `=` value is filterable via `?filter_<col>=<v>`
    /// chips above the list page. Strings, enums, and small-cardinality
    /// columns make the most sense here.
    fn list_filter() -> &'static [&'static str] {
        &["country", "is_default"]
    }

    /// Columns that the list-page `?q=...` search box matches with
    /// `ILIKE`. Defaulted to the text-shaped fields you declared
    /// (`str` / `text`); leave empty if none.
    fn search_fields() -> &'static [&'static str] {
        &["recipient_name", "city", "postal_code"]
    }

    /// Default sort order. Prefix with `-` for descending.
    fn ordering() -> &'static [&'static str] {
        &["-id"]
    }
}
