//! Generated by `rustio-admin startapp cart_item`. Customise freely.

use rustio_admin::{Error, Model, ModelAdmin, Row, RustioAdmin, Value};

#[derive(RustioAdmin)]
pub struct CartItem {
    pub id: i64,
    pub customer_id: i64,
    pub product_id: i64,
    pub quantity: i32,
}

impl Model for CartItem {
    const TABLE: &'static str = "cart_items";
    const COLUMNS: &'static [&'static str] = &["id", "customer_id", "product_id", "quantity"];
    const INSERT_COLUMNS: &'static [&'static str] = &["customer_id", "product_id", "quantity"];

    fn id(&self) -> i64 {
        self.id
    }

    fn from_row(row: Row<'_>) -> Result<Self, Error> {
        Ok(Self {
            id: row.get_i64("id")?,
            customer_id: row.get_i64("customer_id")?,
            product_id: row.get_i64("product_id")?,
            quantity: row.get_i32("quantity")?,
        })
    }

    fn insert_values(&self) -> Vec<Value> {
        vec![self.customer_id.into(), self.product_id.into(), self.quantity.into()]
    }
}

// The `ModelAdmin` impl below customises the admin list / form
// surface for `CartItem`. Every method has a sensible default;
// these starter overrides reflect the fields you declared with
// `--field` at scaffold time. Edit freely.
impl ModelAdmin for CartItem {
    /// Columns shown in the list-page table. Order matches the
    /// `--field` declaration order.
    fn list_display() -> &'static [&'static str] {
        &["id", "customer_id", "product_id", "quantity"]
    }

    /// Columns whose `=` value is filterable via `?filter_<col>=<v>`
    /// chips above the list page. Strings, enums, and small-cardinality
    /// columns make the most sense here.
    fn list_filter() -> &'static [&'static str] {
        // Example: filter the list by a status enum.
        // &["status"]
        &[]
    }

    /// Columns that the list-page `?q=...` search box matches with
    /// `ILIKE`. Defaulted to the text-shaped fields you declared
    /// (`str` / `text`); leave empty if none.
    fn search_fields() -> &'static [&'static str] {
        &[]
    }

    /// Default sort order. Prefix with `-` for descending.
    fn ordering() -> &'static [&'static str] {
        &["-id"]
    }
}
