//! Generated by `rustio-admin startapp payment`. Customise freely.

use rust_decimal::Decimal;
use rustio_admin::{Error, Model, ModelAdmin, Row, RustioAdmin, Value};

#[derive(RustioAdmin)]
pub struct Payment {
    pub id: i64,
    pub order_id: i64,
    pub provider: String,
    pub method: String,
    pub transaction_id: String,
    pub amount: Decimal,
    #[rustio(choices = ["pending", "completed", "failed", "refunded"])]
    pub status: String,
}

impl Model for Payment {
    const TABLE: &'static str = "payments";
    const COLUMNS: &'static [&'static str] = &["id", "order_id", "provider", "method", "transaction_id", "amount", "status"];
    const INSERT_COLUMNS: &'static [&'static str] = &["order_id", "provider", "method", "transaction_id", "amount", "status"];

    fn id(&self) -> i64 {
        self.id
    }

    fn from_row(row: Row<'_>) -> Result<Self, Error> {
        Ok(Self {
            id: row.get_i64("id")?,
            order_id: row.get_i64("order_id")?,
            provider: row.get_string("provider")?,
            method: row.get_string("method")?,
            transaction_id: row.get_string("transaction_id")?,
            amount: row.get_decimal("amount")?,
            status: row.get_string("status")?,
        })
    }

    fn insert_values(&self) -> Vec<Value> {
        vec![self.order_id.into(), self.provider.clone().into(), self.method.clone().into(), self.transaction_id.clone().into(), self.amount.into(), self.status.clone().into()]
    }
}

// The `ModelAdmin` impl below customises the admin list / form
// surface for `Payment`. Every method has a sensible default;
// these starter overrides reflect the fields you declared with
// `--field` at scaffold time. Edit freely.
impl ModelAdmin for Payment {
    /// Columns shown in the list-page table. Order matches the
    /// `--field` declaration order.
    fn list_display() -> &'static [&'static str] {
        &["id", "order_id", "provider", "method", "amount", "status"]
    }

    /// Columns whose `=` value is filterable via `?filter_<col>=<v>`
    /// chips above the list page. Strings, enums, and small-cardinality
    /// columns make the most sense here.
    fn list_filter() -> &'static [&'static str] {
        &["status", "provider", "method"]
    }

    /// Columns that the list-page `?q=...` search box matches with
    /// `ILIKE`. Defaulted to the text-shaped fields you declared
    /// (`str` / `text`); leave empty if none.
    fn search_fields() -> &'static [&'static str] {
        &["transaction_id"]
    }

    /// Default sort order. Prefix with `-` for descending.
    fn ordering() -> &'static [&'static str] {
        &["-id"]
    }
}
