//! Generated by `rustio-admin startapp product_image`. Customise freely.

use rustio_admin::{Error, Model, ModelAdmin, Row, RustioAdmin, Value};

#[derive(RustioAdmin)]
pub struct ProductImage {
    pub id: i64,
    pub product_id: i64,
    pub url: String,
    pub alt_text: String,
    pub position: i32,
    pub is_primary: bool,
}

impl Model for ProductImage {
    const TABLE: &'static str = "product_images";
    const COLUMNS: &'static [&'static str] = &["id", "product_id", "url", "alt_text", "position", "is_primary"];
    const INSERT_COLUMNS: &'static [&'static str] = &["product_id", "url", "alt_text", "position", "is_primary"];

    fn id(&self) -> i64 {
        self.id
    }

    fn from_row(row: Row<'_>) -> Result<Self, Error> {
        Ok(Self {
            id: row.get_i64("id")?,
            product_id: row.get_i64("product_id")?,
            url: row.get_string("url")?,
            alt_text: row.get_string("alt_text")?,
            position: row.get_i32("position")?,
            is_primary: row.get_bool("is_primary")?,
        })
    }

    fn insert_values(&self) -> Vec<Value> {
        vec![self.product_id.into(), self.url.clone().into(), self.alt_text.clone().into(), self.position.into(), self.is_primary.into()]
    }
}

// The `ModelAdmin` impl below customises the admin list / form
// surface for `ProductImage`. Every method has a sensible default;
// these starter overrides reflect the fields you declared with
// `--field` at scaffold time. Edit freely.
impl ModelAdmin for ProductImage {
    /// Columns shown in the list-page table. Order matches the
    /// `--field` declaration order.
    fn list_display() -> &'static [&'static str] {
        &["id", "product_id", "url", "position", "is_primary"]
    }

    /// Columns whose `=` value is filterable via `?filter_<col>=<v>`
    /// chips above the list page. Strings, enums, and small-cardinality
    /// columns make the most sense here.
    fn list_filter() -> &'static [&'static str] {
        &["is_primary"]
    }

    /// Columns that the list-page `?q=...` search box matches with
    /// `ILIKE`. Defaulted to the text-shaped fields you declared
    /// (`str` / `text`); leave empty if none.
    fn search_fields() -> &'static [&'static str] {
        &["alt_text"]
    }

    /// Default sort order. Prefix with `-` for descending.
    fn ordering() -> &'static [&'static str] {
        &["product_id", "position"]
    }
}
